Repository revanced/revanced-releases-api, pull requests merged in 2022-10, with the labels that each got.

#7 feat: resolves #5, resolves #4
  .gitignore
  .vscode/settings.json
  Dockerfile
  README.md
  config.toml
  deploy/docker-compose.yml
  deploy/portainer-stack.yml
  env.sh
  main.py
  modules/models/ResponseModels.py
  mypy.ini
  poetry.lock
  pyproject.toml
  requirements.txt
  run.sh
  src/__init__.py
  src/controllers/Announcements.py
  src/controllers/Auth.py
  src/controllers/Clients.py
  src/controllers/Releases.py
  src/controllers/__init__.py
  src/models/AnnouncementModels.py
  src/models/ClientModels.py
  src/models/GeneralErrors.py
  src/models/ResponseFields.py
  src/models/ResponseModels.py
  src/models/__init__.py
  src/utils/Generators.py
  src/utils/HTTPXClient.py
  src/utils/InternalCache.py
  src/utils/Logger.py
  src/utils/RedisConnector.py
  src/utils/__init__.py
Labels: feature-request

#10 feature: add /changelogs endpoint, resolves #6
  main.py
  src/controllers/Releases.py
  src/models/ResponseFields.py
  src/models/ResponseModels.py
Labels: feature-request

#11 feat: implement clients, authentication, announcement and changelogs
  .gitignore
  .vscode/settings.json
  Dockerfile
  README.md
  config.toml
  deploy/docker-compose.yml
  deploy/portainer-stack.yml
  env.sh
  main.py
  modules/models/ResponseModels.py
  mypy.ini
  poetry.lock
  pyproject.toml
  requirements.txt
  run.sh
  src/__init__.py
  src/controllers/Announcements.py
  src/controllers/Auth.py
  src/controllers/Clients.py
  src/controllers/Releases.py
  src/controllers/__init__.py
  src/models/AnnouncementModels.py
  src/models/ClientModels.py
  src/models/GeneralErrors.py
  src/models/ResponseFields.py
  src/models/ResponseModels.py
  src/models/__init__.py
  src/utils/Generators.py
  src/utils/HTTPXClient.py
  src/utils/InternalCache.py
  src/utils/Logger.py
  src/utils/RedisConnector.py
  src/utils/__init__.py
Labels: feature-request

#14 feat: move endpoints into custom routers, resolves #12
  Dockerfile
  README.md
  app/__init__.py
  app/controllers/Announcements.py
  app/controllers/Auth.py
  app/controllers/Clients.py
  app/controllers/Releases.py
  app/controllers/__init__.py
  app/dependencies.py
  app/main.py
  app/models/AnnouncementModels.py
  app/models/ClientModels.py
  app/models/GeneralErrors.py
  app/models/ResponseFields.py
  app/models/ResponseModels.py
  app/models/__init__.py
  app/routers/__init__.py
  app/routers/announcement.py
  app/routers/auth.py
  app/routers/changelogs.py
  app/routers/clients.py
  app/routers/contributors.py
  app/routers/patches.py
  app/routers/ping.py
  app/routers/root.py
  app/routers/tools.py
  app/utils/Generators.py
  app/utils/HTTPXClient.py
  app/utils/Logger.py
  app/utils/RedisConnector.py
  app/utils/__init__.py
  config.toml
  main.py
  mypy.ini
  poetry.lock
  pyproject.toml
  requirements.txt
  run.py
  run.sh
  src/utils/InternalCache.py
Labels: modification, hacktoberfest-accepted

#16 docs: update description
  config.toml
Labels: documentation, hacktoberfest-accepted

#17 feat: implement cdn mirrors endpoints, closes #15
  app/controllers/Mirrors.py
  app/main.py
  app/models/GeneralErrors.py
  app/models/MirrorModels.py
  app/routers/mirrors.py
  app/utils/Logger.py
  config.toml
Labels: feature-request, hacktoberfest-accepted

#18 feat: implements cdn mirrors endpoints, fix docs, move endpoints to custom routers
  Dockerfile
  README.md
  app/__init__.py
  app/controllers/Announcements.py
  app/controllers/Auth.py
  app/controllers/Clients.py
  app/controllers/Mirrors.py
  app/controllers/Releases.py
  app/controllers/__init__.py
  app/dependencies.py
  app/main.py
  app/models/AnnouncementModels.py
  app/models/ClientModels.py
  app/models/GeneralErrors.py
  app/models/MirrorModels.py
  app/models/ResponseFields.py
  app/models/ResponseModels.py
  app/models/__init__.py
  app/routers/__init__.py
  app/routers/announcement.py
  app/routers/auth.py
  app/routers/changelogs.py
  app/routers/clients.py
  app/routers/contributors.py
  app/routers/mirrors.py
  app/routers/patches.py
  app/routers/ping.py
  app/routers/root.py
  app/routers/tools.py
  app/utils/Generators.py
  app/utils/HTTPXClient.py
  app/utils/Logger.py
  app/utils/RedisConnector.py
  app/utils/__init__.py
  config.toml
  main.py
  mypy.ini
  poetry.lock
  pyproject.toml
  requirements.txt
  run.py
  run.sh
  src/utils/InternalCache.py
Labels: feature-request, hacktoberfest-accepted
